"""Json

迁移 ID: 71a406765b7a
父迁移: 25b14ed0ad3c
创建时间: 2025-08-21 15:37:36.069585

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "71a406765b7a"
down_revision: str | Sequence[str] | None = "25b14ed0ad3c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("suggarchat_memory_data", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "memory", sa.JSON(), server_default=sa.text("'{}'"), nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "sessions", sa.JSON(), server_default=sa.text("'[]'"), nullable=False
            )
        )
        batch_op.drop_column("memory_json")
        batch_op.drop_column("sessions_json")

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("suggarchat_memory_data", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sessions_json", sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column("memory_json", sa.TEXT(), nullable=False))
        batch_op.drop_column("sessions")
        batch_op.drop_column("memory")

    # ### end Alembic commands ###
